### ISSUE TITLE
Provide a way to configure the Tenant ID for the authentication

### ISSUE THREAD

**Issue by liguori** [microsoft/ado-codespaces-auth#14]
I was using the extension in combination with https://github.com/microsoft/codespace-features/tree/main/src/external-repository in order to clone an Azure DevOps repo in Codespaces. Unfortunately, I was not able get authorized to my repo.

The authorization failed because I have used an account present on multiple Entra ID tenants and the Azure DevOps Organization for the repo to be used was on a specific tenant. This extension does not allows to specify the tenant so in absence of it the authentication occurs on the default tenant. When the extension is loaded the authentication challenge start with this URL:
https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize...

The user must be able to configure the tenant id (optional) in order to authenticate against this URL:
https://login.microsoftonline.com/[tenantIdFromConfigurationHere]/oauth2/v2.0/authorize...
 
The Microsoft Authentication Provider for VS Code used by this extension allows to specify the tenant for the authentication with a "magic scope" that should be something like "VSCODE_TENANT: aaa-bbb-ccc"
Ref: https://github.com/microsoft/vscode/blob/56f9e01216f191f7d6b8e32d32b62c816e5a6f77/extensions/microsoft-authentication/src/AADHelper.ts#L648
 
I was thinking to an Environment variable named "AZDO_TENANT_ID" that can be used to build the additional scope 'VSCODE_TENANT:xyz' in this place:
https://github.com/microsoft/ado-codespaces-auth/blob/82aba97a7461c70248c734da83d96578604f7039/src/extension.ts#L55

I started to draft some changes here: https://github.com/liguori/ado-codespaces-auth/commit/099efd689ccbb898ea5d17776c82daddb6a83c4a

**Comment by ronakj** [comment]
To me it makes more sense to put this in extension preferences otherwise it ends up being a random environment variable which you will only know about after reading documentation. See example here https://github.com/microsoft/vscode-azure-account/blob/cd4fe355c3b8741b0d8cd530775c562eb641b2aa/package.json#L137C1-L155C19. 

You can customize your devcontainer with VSCode settings so you should be still be able to configure this per repo. https://containers.dev/supporting#visual-studio-code

**Comment by liguori** [comment]
I have completed the changes and tested/debugged the extension by providing a tenantID as setting and seems to work. 
I was unable to test the E2E flow with devContainers and the '[external-repository](https://github.com/microsoft/codespace-features/tree/main/src/external-repository)' feature but as pointed by @ronakj it should work with VSCode settings in devContainer.

Here the PR: https://github.com/microsoft/ado-codespaces-auth/pull/15

**Comment by liguori** [comment]
Resolved by https://github.com/microsoft/ado-codespaces-auth/pull/15 that bumps the extension to 1.2

**Comment by ronakj** [comment]
This is now released in version 1.2.1 including your fix @liguori. Thank you for the contribution!
