### ISSUE TITLE
Authentication gets stuck/fails in desktop VS Code

### ISSUE THREAD

**Issue by samruddhikhandale** [microsoft/ado-codespaces-auth#20]
Hi 👋 

Since yesterday (or that's when we first ran into it), we are unable to authenticate with the extension.

Repro steps: 

1. Create a codespace with the extension installed
2. Open the codespace in local VS Code (Version: 1.91.0 (Universal))
3. Click on “Allow” and sign with the Microsoft account
![Image](https://github.com/user-attachments/assets/6a6321ce-c70b-4531-b20d-f6467bc10920)

3. However, it gets stuck while signing in the browser👇 

https://github.com/user-attachments/assets/149c3d2a-67ef-41f3-a310-b4aea67f0a8d

Note: In the browser, the signing continues to spin but doesn't succeed.

I do remember seeing some "authenctication failed" prompt in VS Code, but I couldn't repro it again to share it here.

Can you please help us with this issue? It's impacting ours devs day-to-day flow. Thank you! 

Current workaround: If we open the codespace in browser, then the authentication is successful. Hence, it seems like the desktop extension is not able to communicate with the browser? (else, it some caching issue)

**Comment by markphip** [comment]
It is still working for me. I did see some message about being signed out but it still worked and in the status bar it still showed "Authenticated" next to the Azure DevOps icon

![Image](https://github.com/user-attachments/assets/c4d011fa-5eb8-4082-9281-791bedea7145)

**Comment by markphip** [comment]
There is an ADO Codespaces Auth section in the Output window where you could look for errors

**Comment by markphip** [comment]
My VS Code on MacOS also updated to 1.91.1 while I was testing and that version also seems to be working

**Comment by markphip** [comment]
You can run this command from Terminal in the Codespace to confirm you get a token from the extension: `~/ado-auth-helper get-access-token` 

It should print a token to the terminal stdout

**Comment by ronakj** [comment]
We haven't really changed anything in the extension recently, so it's most likely a VSCode issue. Check if you are already signed into a microsoft account (from the accounts menu in VSCode), if yes maybe try signing out of all of them and then try signing in again.

If that doesn't resolve it, do send the logs from the Output window for both "Microsoft authentication" and "ADO Codespaces Auth". You can find them here -

![image](https://github.com/user-attachments/assets/76efdaa5-6c83-4f60-8823-3ab17c5ee3b0)

**Comment by samruddhikhandale** [comment]
Thank you for providing us with debugging steps, we were able to resolve the issue. 

In our scenario, we were running `yarn` and `npm` commands form `.csproj` (ie we didn't use bash shell). Hence, the aliasing wasn't working which resulted into our project not using the authentication token generated by the helper. 

In our projects, we are now directly using `/usr/local/bin/run-npm.sh` to fix this. thanks!
